@startuml packages
set namespaceSeparator none
package "base_systems" as base_systems {
}
package "main" as main {
}
package "params" as params {
}
package "qs" as qs {
}
package "servers" as servers {
}
package "system_stats" as system_stats {
}
package "systems" as systems {
}
package "visitor" as visitor {
}
base_systems --> params
base_systems --> qs
base_systems --> servers
base_systems --> system_stats
base_systems --> visitor
main --> params
main --> systems
main --> visitor
qs --> params
qs --> visitor
servers --> params
servers --> visitor
systems --> base_systems
systems --> params
systems --> servers
systems --> visitor
@enduml
